POST {{$dotenv BASE_URL}}/assistants?api-version={{$dotenv OPENAI_VERSION}} HTTP/1.1
Content-Type: application/json
api-key: {{$dotenv OPENAI_KEY}}

{
    "instructions": "You are an AI model that empowers every person and every organization on the planet to achieve more.",
    "model": "gpt-4-turbo-test"
}

###

GET {{$dotenv BASE_URL}}/threads?api-version={{$dotenv OPENAI_VERSION}} HTTP/1.1
Content-Type: application/json
api-key: {{$dotenv OPENAI_KEY}}


###

POST {{$dotenv EMAIL_URI}} HTTP/1.1
Content-Type: application/json

{
    "to":"alemor@microsoft.com; vsantana@microsoft.com; Andres.Padilla@microsoft.com",
    "content":"This is a test email from the Email Assistant API."
}

###

POST {{$dotenv CALENDAR_EMAIL_URI}} HTTP/1.1
Content-Type: application/json

{
    "type":"email",
    "email": {
        "to":"alemor@microsoft.com",
        "emailSubject":"Test Email",
        "emailContent":"This is a test email from the Email Assistant API."
    }
}

###

POST {{$dotenv CALENDAR_EMAIL_URI}} HTTP/1.1
Content-Type: application/json

{
    "type":"event",
    "email": {        
        "eventSubject":"Test Invite",
        "startTime": "2024-16-01T12:00:00",
        "endTime": "2024-16-01T12:30:00",
        "eventAttendees": "andredewes@microsoft.com",
        "eventContent":"This is a test email from the Email Assistant API."
    }
}