POST {{$dotenv BASE_URL}}/assistants?api-version={{$dotenv OPENAI_VERSION}} HTTP/1.1
Content-Type: application/json
api-key: {{$dotenv OPENAI_KEY}}

{
    "instructions": "You are an AI model that empowers every person and every organization on the planet to achieve more.",
    "model": "gpt-4-turbo-test"
}

###

GET {{$dotenv BASE_URL}}/threads?api-version={{$dotenv OPENAI_VERSION}} HTTP/1.1
Content-Type: application/json
api-key: {{$dotenv OPENAI_KEY}}


###

POST {{$dotenv EMAIL_URI}} HTTP/1.1
Content-Type: application/json

{
    "to":"alemor@microsoft.com; vsantana@microsoft.com; Andres.Padilla@microsoft.com",
    "content":"This is a test email from the Email Assistant API."
}